# coding: utf-8

# flake8: noqa
"""
    Client

    Client Requests log registration  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
